### ISSUE TITLE
Running a revel project on travis-ci?

### ISSUE THREAD

**Issue by pvdvreede** [revel/revel#308]
Just created my first revel project and I have added some tests and am trying to get the tests running through Travis-CI.

I have the following `.travis.yml`:

``` yml

---
language: go

go:
- 1.1

before_script: go install github.com/robfig/revel
script: $HOME/gopath/bin/revel test github.com/pvdvreede/dateable
```

No matter how I tweak the `script:` portion  (ie. remove or change the path to the `revel` binary) it keeps saying that it cannot find the revel binary to run the tests. 

Seeing as this is my first Go project I am wondering if there is some convention I am missing? Obviously there is some abstraction from the normal `go test` command so not sure if there is something I am missing that relates to revel, or just Go in general.

Just wondering if you can point me in the right direction for how to run revel projects through Travis-ci specifically?

Thanks.
