### ISSUE TITLE
First thought on revel

### ISSUE THREAD

**Issue by azr** [revel/revel#636]
Hi there,

I'm trying go/revel by creating a very simple REST/CRUD api.
I'd like to make cool apps using it so more people can say "hey look we can do cool stuff out of this !"
I also think that this is future tech and that the wheel can be reviewed here.

I love revel, but here is what I thought was to rethink :

1/ Weird naming/structure/extension types
- I would put the conf/ directory into the app/ directory because the config is inherent to the app
- conf/app.conf <- here I would have used conf/parameters.yml, and have a yaml parser load conf objects
  - yaml is much easier to read for me and my editor, it's a standard
  - this file would only contain parameters for the local deployment of the app
  - the fact that the directory is named conf/ is pretty clear
  - it should be [12 factor config](http://12factor.net/config) compliant
- conf/routes <- I would have used conf/routing.yml
  - with a route looking something like this :

``` yaml
article_show: # <- this is the route name
  path:  /articles/{culture}/{year}/{title}.{_format}
  defaults: { _format: html, _action: Articles.Show }
  requirements:
      _method: GET
      _format:  html|json|xml # <- when the data is asked in json return json 
      culture:  en|fr|ru
      year:     int # rest is string by default
# so when asking /articles/en/42/bar the fw searches for an html template file and displays it
# same for /articles/en/42/bar.html
# /articles/en/42/bar.json will return a marshall of everything returned by ctrlr
# /articles/jp/zzz/bar.html -> 404
# etc.
```
- Index.html is actually code
  - an HTML file should be plain dumb text
  - that file should be Index.html.`fancyname`
  - A `fancyname` parser would then transform this into html to shove into the socket
  - we could define that into a conf/framework.yml that won't depend on environment

``` yaml
#conf/framework.yml
framework:
    templating: ['fancyname']
#then I can have a views/Ctrl/Action.html.fancyname file woohoo !
# Fallback to views/Ctrl/Action.html if not found !
```

2/ Controllers should always get what we tell them

Here is a Controller returning the "message" parameter.

```
$ curl 'http://localhost:9999' --data 'message=foo'
"foo"
# Yes !
$ curl 'http://localhost:9999' --data-binary 'message=foo'
"foo"
# Yes !
$ curl 'http://localhost:9999' --data-binary '{"message" : "asd"}'
""
# Nope !
$ curl 'http://localhost:9999/' -H 'Content-Type: application/json, text/javascript, */*' -H 'Accept: application/json' -H 'X-Requested-With: XMLHttpRequest' --data-binary $'------WebKitFormBoundaryvGqfd7Srd1gMDaUd\r\nContent-Disposition: form-data; name="message"\r\n\r\nfoo\r\n------WebKitFormBoundaryvGqfd7Srd1gMDaUd--\r\n'
""
# Nope ! ( this was forged by PostMan: https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm)

$ curl 'http://localhost:9999/' -H 'Content-Type: application/json, text/javascript, */*, application/x-www-form-urlencoded' --data-binary 'message=foo'
""
# Nope ! ( same here )

```

When used with a normal js framework you'll always get JSON objects or those weird WebKitFormBoundary stuff, so I think this is an issue.

3/ Have something to store data that is production ready and easy to dev with
- ORM or not but something, make a choice
- I have absolutely no idea on this but I think it's totally okay to make something new because people getting here will be early adopters/discoverers, they want cool new stuf !
- please just let it be easy to understand/maintain/create/pass over
- and superfast
- lets' not forget about migrations
- have a documentation that tells how to go production/maintain/migrate super easily 

4/ Let frontend frameworks do frontend stuff
- less/scss processing is easy on node or any other web js framework, don't bother doing it again.

5/ Promote reusability
- Think of some way to create reusable web components for Go that won't depend on the framework

...And that's all, yet.
It's an opening for conversation, I'm really eager to see all of this working !!
Also, I can contribute on my very small free time.

Thanks ! :)
