### ISSUE TITLE
data migrations

### ISSUE THREAD

**Issue by rtm7777** [revel/revel#889]
What is the best way to create script for database init or something else in Revel?

Something like it in Rails rake:

```
  rake db:seed
```

I want to create folder in project named `scripts`, with several scripts for initialize db data for development and others. Scripts should have an access to initialized revel app, its methods and db connection.

We have cmd tool, it can run all test and separately one by one. Maybe we can do something like this for scripts? Like:

```
revel runscript script_name
```

Also we have a jobs, but I want run this scripts separately from app.

Thanks!

**Comment by anonx** [comment]
Hi, @rtm7777. I like the idea of running custom [revel/cmd](https://github.com/revel/cmd) commands. But I think it should be something more than just a script runner. Our own format of "revel tool" package, probably. And implement existing commands such as `run`, `build`, `package`, etc. in a form of those packages. So, [revel/cmd](https://github.com/revel/cmd) will be more modular and extendible.

@revel/core, thoughts?

**Comment by notzippy** [comment]
@anonx Agreed, 

This is a familiar use case as well, basically a run once command passed into the application when you start the web application. A technique you can use is to export an environment variable APP_VERSION and then the application. The value of "APP_VERSION" is available from the config by doing a `revel.Config.StringDefault("app.APP_VERSION", "(not set)")`, adding a function to revel.OnAppStart to read the app.APP_VERSION and compare it to a known value you have a way to hook in some initialization code.

**Comment by pedromorgan** [comment]
I use fabric a lot..

If me mashed up fabric into revel, like travix.yml stlye.. we'd be cool

**Comment by pedromorgan** [comment]
Another example is to map does based on version ,.

Maybe even a custom command in app. Or added in config...

But this is definite what we want..

**Comment by pedromorgan** [comment]
Xref to revel/cmd

https://github.com/revel/cmd/pull/22

**Comment by brendensoares** [comment]
@anonx I like this idea.

@pedromorgan What do you mean mashup fabric into revel? I don't want revel to depend on any other language platform like fabric in python.

**Comment by anonx** [comment]
https://github.com/revel/rfcs/pull/2 is a proposal to transform `revel` command into a files watcher and task runner. Every project will have `.revel.yml` in the format like:
```yml
init:
  --- # Add your list of what should be done every time `revel run` is started.
  - npm install coffeescript
watchers:
  --- # Include a list of commands that are expected to be executed on files' change.
  -
    --- # Recompile my app every time my controllers are modified.
    path: app/controllers/*.go
    before:
    action:
      - go generate path/to/myapp
      - go build path/to/myapp
      - go run path/to/myapp
    after:
  -
    --- # Compile my coffee script files to JS.
    path: app/assets/coffee/*
    action:
      - coffeescript -smth -smth_else
```
Simply saying, the only responsibility of `revel` will be watching files and executing commands requested in `.revel.yml`. Thus, it will close #620, too.
